[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'numpy']

[project]
name = 'dsharp_opac'
version = '1.1.13'
description = 'python routines to calculate mie opacities'
readme = { file = 'README.md', content-type = 'text/markdown' }
authors = [
    { name = "Til Birnstiel & DSHARP collaboration", email = "til.birnstiel@lmu.de" },
]
license = { file = 'LICENSE' }
requires-python = ">=3.10"
dependencies = ['numpy', 'scipy', 'matplotlib', 'astropy', 'mpmath', 'setuptools']

[project.urls]
Repository = "https://github.com/birnstiel/dsharp_opac/"

[tool.cibuildwheel]
skip = ["cp314t-*"]
build-verbosity = 1
test-command = [
    "python -c 'import dsharp_opac'",
]

[tool.cibuildwheel.windows]
# adapted from numpy
config-settings = {setup-args = ["--vsenv"], build-dir="build"}

[tool.cibuildwheel.macos]
before-all = [
    "brew install gfortran",
]